Update skippedJobs.yml

diff --git a/.github/workflows/skippedJobs.yml b/.github/workflows/skippedJobs.yml
--- a/.github/workflows/skippedJobs.yml
+++ b/.github/workflows/skippedJobs.yml
@@ -1,4 +1,4 @@
-name: Skipped Jobs Workflow
+name: Sequential Jobs Workflow
 
 on:
   push:
@@ -33,11 +33,13 @@ jobs:
 
   job4:
     name: Job 4
-    if: ${{ always() }}
-    needs: job3
     runs-on: ubuntu-latest
+    needs: job3  # Job 4 depends on Job 3
+    if: ${{ always() }}  # Ensures that job4 runs no matter what happens with job3
     steps:
       - name: Step 1 in Job 4 - Waiting for 30 seconds
         run: echo "Waiting for 30 seconds..." && sleep 60
-      - name: Step 2 in Job 4 - Actual Execution
-        run: echo "Running Job 4 after waiting"
+      - name: Step 2 in Job 4 - Always Fail
+        run: |
+          echo "This job is forced to fail."
+          exit 1  # Force the job to fail every time
