Update skippedJobs.yml

diff --git a/.github/workflows/skippedJobs.yml b/.github/workflows/skippedJobs.yml
--- a/.github/workflows/skippedJobs.yml
+++ b/.github/workflows/skippedJobs.yml
@@ -40,10 +40,10 @@ jobs:
     steps:
       - name: Step 1 in Job 4 - Waiting for 30 seconds
         run: echo "Waiting for 30 seconds..." && sleep 60
-      - name: Step 2 in Job 4 - Always Fail
-        run: |
-          echo "This job is forced to fail."
-          exit 1  # Force the job to fail every time
+      # - name: Step 2 in Job 4 - Always Fail
+      #   run: |
+      #     echo "This job is forced to fail."
+      #     exit 1  # Force the job to fail every time
 
   # More Parallel Skipped Jobs
   job5:
